= Groovydoc Maven Plugin

It turns out, that the javadoc plugin for Maven doesn't actually generate anything useful for Groovy projects. Further,
when releasing artifacts to Apache Maven Central, you actually need Javadocs. So generating Groovydocs (which
generates Groovy and Javadocs) turns out to be a fairly good idea, but the only method for doing it turned out to
be an Ant task, which is a whole lot of crazy to have in your parent poms.

This plugin encapsulates the functionality of the Groovydoc plugin in its simplest form, package exclusions are not
supported, it defaults to public APIs.

== Enabling the plugin

Including the following in your POM will enable groovy docs to be generated with a -javadoc.jar extension and
javadoc classifier

[source,xml,index=2]
----
<plugin>
  <groupId>com.bluetrainsoftware.maven</groupId>
  <artifactId>groovydoc-maven-plugin</artifactId>
  <version>1.1</version>
  <executions>
    <execution>
      <id>attach-docs</id>
      <goals>
        <goal>attach-docs</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

== Overrides

All of the known overrides can be specified, some do not work however (such as specifying excludes and includes). If
there is a calling for it, I can implement it.
